export const POST_FEEDBACK = {
	SUCCESS: "POST_FEEDBACK_SUCCESS",
	STARTED: "POST_FEEDBACK_STARTED",
	FAILURE: "POST_FEEDBACK_FAILURE"
};

export const POST_TAG = {
	SUCCESS: "POST_TAG_SUCCESS",
	FAILURE: "POST_TAG_FAILURE"
};

export const GET_USER_TEAMMATE = {
	SUCCESS: "GET_USER_TEAMMATE_SUCCESS",
	FAILURE: "GET_USER_TEAMMATE_FAILURE",
	STARTED: "GET_USER_TEAMMATE_STARTED"
};
